### ISSUE TITLE
Dark theme not applying on system apps.

### ISSUE THREAD

**Issue by vishalscodes** [phstudio2/Darktheme#11]
Phone Model: Honor 7X
Android Version: 9

So although this app works great for non-system apps, it does not apply the dark theme to system apps like Settings, Messaging, etc.

Any help is appreciated.

![Screenshot_20240413_082349_com android settings](https://github.com/phstudio2/Darktheme/assets/104351431/000ac30a-8058-42f3-ae2c-771fb73e6e92)

**Comment by pa238** [comment]
Thank you for reporting this bug, after testing our app on a Google Pixel 6 with Android 9.0 (Pie) - API 28 everything worked fine, so I think it's a bug in the Honor framework. Therefore, it cannot be fixed programmatically, so I am closing this issue.
