### ISSUE TITLE
Compatibility for Huawei Android 9 smartphones?

### ISSUE THREAD

**Issue by jwiesel** [phstudio2/Darktheme#2]
Hi,
thanks for providing this app on F-Droid!

I installed it on a Huawei P20 Lite (ANE-LX1).
* Android 9
* EMUI-Version 9.1

Unfortunately the theme does not change (e.g. settings).
Can you add support for Huawei Android 9 smartphones?

Please let me know, if there is anything I can test.
Thanks!

**Comment by pa238** [comment]
Thank you for reporting the bug. I have not tested the app on HUAWEI devices yet. But the app does not require any GSM, so it should work on these devices as well.
The app was tested on Android 9 (API 28) and worked normally.

In the future, I plan to upload the app to HUAWEI's AppGallery, so I would be glad if you could provide more information about the bugs on HUAWEI devices.
