### ISSUE TITLE
Compatibility for Samsung Android 6 Smartphones

### ISSUE THREAD

**Issue by jwiesel** [phstudio2/Darktheme#3]
Hi,
thanks for providing this app on F-Droid!

I installed it on a Samsung Galaxy S5 (SM-G900F).
* Android 6

When trying to switch from light to dark theme the app crashes.
If I start the app again, it shows to be in Dark mode, but unfortunately the theme does not change (e.g. settings).
Can you add support for Samsung Android 6 smartphones?

Please let me know, if there is anything I can test.
Thanks!

**Comment by pa238** [comment]
Thank you for reporting the error. I just ran a test on a Google Pixel 5 - Android 6 (API 23) and everything worked fine.

Just for reference on Android 6 you can't change the color settings when in dark mode.

If you get a bug list I could address this further, but for now I will have to close this issue.
